# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\x12\x03\x61pi\"&\n\x0bTaskRequest\x12\x17\n\x04task\x18\x01 \x01(\x0b\x32\t.api.Task\"+\n\x0cTaskResponse\x12\x1b\n\x06\x66uture\x18\x01 \x01(\x0b\x32\x0b.api.Future\"&\n\x14TaskCompletedRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\x0c\"\x17\n\x15TaskCompletedResponse\"/\n\x10GetResultRequest\x12\x1b\n\x06\x66uture\x18\x01 \x01(\x0b\x32\x0b.api.Future\"#\n\x11GetResultResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\"(\n\x04Task\x12\x0e\n\x06taskId\x18\x01 \x01(\x0c\x12\x10\n\x08taskData\x18\x02 \x01(\x0c\" \n\x06\x46uture\x12\x16\n\x0eresultLocation\x18\x01 \x01(\t2\x8d\x01\n\x0cSchedulerApi\x12\x33\n\nSubmitTask\x12\x10.api.TaskRequest\x1a\x11.api.TaskResponse\"\x00\x12H\n\rTaskCompleted\x12\x19.api.TaskCompletedRequest\x1a\x1a.api.TaskCompletedResponse\"\x00\x32\x7f\n\tWorkerApi\x12<\n\tGetResult\x12\x15.api.GetResultRequest\x1a\x16.api.GetResultResponse\"\x00\x12\x34\n\x0b\x45xecuteTask\x12\x10.api.TaskRequest\x1a\x11.api.TaskResponse\"\x00\x62\x06proto3'
)




_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='api.TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='api.TaskRequest.task', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=56,
)


_TASKRESPONSE = _descriptor.Descriptor(
  name='TaskResponse',
  full_name='api.TaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='future', full_name='api.TaskResponse.future', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=101,
)


_TASKCOMPLETEDREQUEST = _descriptor.Descriptor(
  name='TaskCompletedRequest',
  full_name='api.TaskCompletedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='api.TaskCompletedRequest.taskId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=141,
)


_TASKCOMPLETEDRESPONSE = _descriptor.Descriptor(
  name='TaskCompletedResponse',
  full_name='api.TaskCompletedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=166,
)


_GETRESULTREQUEST = _descriptor.Descriptor(
  name='GetResultRequest',
  full_name='api.GetResultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='future', full_name='api.GetResultRequest.future', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=215,
)


_GETRESULTRESPONSE = _descriptor.Descriptor(
  name='GetResultResponse',
  full_name='api.GetResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='api.GetResultResponse.result', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=252,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='api.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='api.Task.taskId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskData', full_name='api.Task.taskData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=294,
)


_FUTURE = _descriptor.Descriptor(
  name='Future',
  full_name='api.Future',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultLocation', full_name='api.Future.resultLocation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=328,
)

_TASKREQUEST.fields_by_name['task'].message_type = _TASK
_TASKRESPONSE.fields_by_name['future'].message_type = _FUTURE
_GETRESULTREQUEST.fields_by_name['future'].message_type = _FUTURE
DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['TaskResponse'] = _TASKRESPONSE
DESCRIPTOR.message_types_by_name['TaskCompletedRequest'] = _TASKCOMPLETEDREQUEST
DESCRIPTOR.message_types_by_name['TaskCompletedResponse'] = _TASKCOMPLETEDRESPONSE
DESCRIPTOR.message_types_by_name['GetResultRequest'] = _GETRESULTREQUEST
DESCRIPTOR.message_types_by_name['GetResultResponse'] = _GETRESULTRESPONSE
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['Future'] = _FUTURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.TaskRequest)
  })
_sym_db.RegisterMessage(TaskRequest)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.TaskResponse)
  })
_sym_db.RegisterMessage(TaskResponse)

TaskCompletedRequest = _reflection.GeneratedProtocolMessageType('TaskCompletedRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOMPLETEDREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.TaskCompletedRequest)
  })
_sym_db.RegisterMessage(TaskCompletedRequest)

TaskCompletedResponse = _reflection.GeneratedProtocolMessageType('TaskCompletedResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOMPLETEDRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.TaskCompletedResponse)
  })
_sym_db.RegisterMessage(TaskCompletedResponse)

GetResultRequest = _reflection.GeneratedProtocolMessageType('GetResultRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETRESULTREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.GetResultRequest)
  })
_sym_db.RegisterMessage(GetResultRequest)

GetResultResponse = _reflection.GeneratedProtocolMessageType('GetResultResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESULTRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.GetResultResponse)
  })
_sym_db.RegisterMessage(GetResultResponse)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.Task)
  })
_sym_db.RegisterMessage(Task)

Future = _reflection.GeneratedProtocolMessageType('Future', (_message.Message,), {
  'DESCRIPTOR' : _FUTURE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.Future)
  })
_sym_db.RegisterMessage(Future)



_SCHEDULERAPI = _descriptor.ServiceDescriptor(
  name='SchedulerApi',
  full_name='api.SchedulerApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=331,
  serialized_end=472,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubmitTask',
    full_name='api.SchedulerApi.SubmitTask',
    index=0,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TaskCompleted',
    full_name='api.SchedulerApi.TaskCompleted',
    index=1,
    containing_service=None,
    input_type=_TASKCOMPLETEDREQUEST,
    output_type=_TASKCOMPLETEDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULERAPI)

DESCRIPTOR.services_by_name['SchedulerApi'] = _SCHEDULERAPI


_WORKERAPI = _descriptor.ServiceDescriptor(
  name='WorkerApi',
  full_name='api.WorkerApi',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=474,
  serialized_end=601,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetResult',
    full_name='api.WorkerApi.GetResult',
    index=0,
    containing_service=None,
    input_type=_GETRESULTREQUEST,
    output_type=_GETRESULTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExecuteTask',
    full_name='api.WorkerApi.ExecuteTask',
    index=1,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKERAPI)

DESCRIPTOR.services_by_name['WorkerApi'] = _WORKERAPI

# @@protoc_insertion_point(module_scope)
