NOTCOMPLETED = b"NOTCOMPLETED"
ERROR = b"ERROR"
WAITTIMEFORPOLLINGRESULT = 0.1  # 100ms
SCHEDULINGMODE_RANDOM = "Random"
SCHEDULINGMODE_ROUNDROBIN = "RoundRobin"
WAIT_TIME_FOR_FUTURE_FROM_WORKER = 2  # 2 seconds