name: cs244b CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cs244b-CI:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Create and activate environment
        run: |
          conda create --name cs244b-env python=3.9 -y
          echo "CONDA_ENV_NAME=cs244b-env" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: |
          $CONDA/bin/activate $CONDA_ENV_NAME
          pip install -r requirements.txt
        shell: bash

      - name: Compile protos
        run: ./compile_proto.sh

      - name: Lint with flake8
        run: |
          $CONDA/bin/activate $CONDA_ENV_NAME
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        shell: bash

      # ... rest of the steps remain the same ...

      - name: Stop worker servers (PowerOfTwo mode)
        run: pkill -f worker_server.py
        shell: bash
